### ISSUE TITLE
AWS 기술지원 고객요청 분석하기

### ISSUE THREAD

**Issue by tov324-archived** [booit/aws#1]
AWS 기술 지원 계획을 세우기 위해, 고객이 요청하는 주요 AWS 작업들의 유형을 분석합니다.

- 대상 플랫폼: `크몽`

@bksanjuk
분석 내용은 본 이슈의 댓글로 달아주세요.

**Comment by bksanjuk** [comment]
크몽 AWS 및 Cloud 서비스 구축 문의 사항 정리 
2020.07월 ~ 2021.08월

- Cloud 서비스 지원 
1. azure beginner 가이드 작성 요청 

2. GPU 셋팅 및 AI 설정 요청 

3. EC2 에 빌드된 파일을 배포 가능 하게끔 요청? 

4. AWS LB 설정 요청 (네이버 페이 사용시 일부 도메인의 경우 HTTP 로 통신해야 하지만 AWS APP LB 사용시 모든 디렉토리가 HTTPS 로 통신되어
정상적으로 네이버 페이를 사용할수 없는 현상 발생)

5. 동영상 사이트 운영시 특정시간에 트래픽이 몰려서 장애가 나는 현상 발생 

6. 이미지/동영상 서버 구축 문의 
 1) 이미지/동영상 트래픽으로 서버가 죽지않고 빠르게 뜰수 있는 서버구축방법 및 세팅 가능 한가요?
 2) 월간 트래픽량이 100TB정도 일때 서버비용( 세팅비, 설치비, 월간유지비)등 대략 얼마정도 들어가나요?
 3) 가능하면 세팅은 몇일 정도 걸리나요?

7. Wordpress 사이트 속도 문제로 인한 개선 요청 

8. 다국어 사이트 리다이렉트 
ex) 중국에서 접속시 자동적으로 중문사이트( parksystems.com/cn) 로 접속되어 중국의 영어 사용자들이 접속 하지 못하는 현상 발생
중국에서도 영문 사이트 / 중문 사이트 선택 하여 접속 하게 가능할수 있는지 ? 

9. AWS 리전 접속 이슈 
parksystems.com 는 캘리포니아 리전을 사용 홍콩리전에도 사용 하게 하고 싶다는 요청

10. AWS 장애 처리 요청 
결제카드 교체후 결제 누락으로 인하여 서비스 중지후 ec2가 부팅후 정상 부팅 되다 나중에는 접속할수 없는 이슈가 발생함

11. AWS 인프라 구축 요청 (스타트 업 요청 자료라 수정 없이 자료 내용을 그대로 올립니다.)

안녕하세요? 저희는 모바일앱 서비스를 개발하고 있는 스타트업입니다.
앱은 개발중이며 서비스를 앞두고 있는데요.
현재 aws를 개발환경으로 사용중에 있습니다.
앞으로 서비스를 하기 위해 '라이브환경에서 aws인프라를 구축'하는 부분에 경험이 없어서 도움이 필요합니다.

다음달에 출시가 목표인 상황이고요
저희 내부개발자와 커뮤니케이션 후 진행을 했으면 하는데, 프로세스가 결제를 먼저 해야 하는지 궁금하네요
필요한 내용은 아래와 같습니다. 진행이 가능하실지 문의드립니다.


작업내용

<서버 구조>
1. 외부 api 서버
어플리케이션 : Java, Spring Boot
DB : mysql
형상관리 : github

2. 내부 core 서버
어플리게이션 : Python, Flask
DB : 없음
형상관리 : github

3. CDN 서버

<필요 사항>
무중단 배포
blue-green 방식 배포

외부-내부 서버간 통신 구조
외부 서버 오토 스케일링
내부 서버 오토 스케일링
DNS 연결




12. 이밴트 사이트 (랜딩페이지) / 이벤트 사이트가 1개월 사용하지만 사용자 폭주로 인한 사이트 다운에 민감함 
ex)
안녕하세요. GCP에 웹서버를 구축해서 이벤트용 사이트를 워드프레스로 개발하고 운영하려고합니다. 
서버구축+이벤트 기간 1개월정도 동안 기술지원 가능할지 문의 드립니다.



- 보안 
1. AWS VPN 설치 및 서버실 보안 장비 연결 
2. 해킹공격 으로 인하여 핸드폰 인증 사이트 연결 불가 현상 해결 요청 (WAF 설정필요)



- Linux Service 기술지원
1. 우분투 nginx aws 설치 지원 
2. ftp 오류로 인한 접속 불가 현상 
3. wordpress의 ssl설정
4. php,db 가상호스트설정 ftp 서버설치
5. 공유 폴더 생성 요청 (개발자 + 운영자 + 디자이너) 
6. AWS 라이트세인 nginx + php + wordpress + nextcloud 설치 요청
7. 레거시 장비 AWS 로 서비스 이관 (LAMP 환경 및 LEMP 환경)
8. EC2 에 apache + tomcat 설치 요청 
9. lightsail 장애 처리 요청 (리눅스 시스템 과부하로 인한 web-service down 현상 발생)



- APP 기술 지원 
1. flutter 앱도 aws 셋팅
2. WS Lambda에 크롤링 JS파일이 정상적으로 구동이 되지 않는 현상
3. ERP 로 개발된 Java 기반 어플리케이션이 정상적으로 되고 있으나 간헐적으로 접속이 안되는 현상발생
- 동일한 문제가 있는 Web Service 는 AWS 서버 증설로 문제 해결 
4. 로컬에서 사용하는 node.js 프로그램을 ec2 에서 실행시 정상적으로 실행 안되는 현상 발생



- 모니터링 
1. 홈페이지의 서브도메인별로 트래픽 모니터링
